import { Candidate } from "@/lib/types";
import { GRADE, FORMAT, READINESS_STATUS, PIPELINE_STAGE } from "./dictionaries";

export const mockCandidates: Candidate[] = [
  {
    id: "c1",
    name: "Alexey Smirnov",
    role: "Frontend Developer",
    grade: GRADE.SENIOR,
    format: FORMAT.REMOTE,
    rate: 45,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Redux"],
    readinessScore: 95,
    readinessStatus: READINESS_STATUS.READY,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    about: "Experienced frontend dev specializing in React and Next.js ecosystems.",
  },
  {
    id: "c2",
    name: "Maria Ivanova",
    role: "Backend Developer",
    grade: GRADE.MIDDLE,
    format: FORMAT.REMOTE,
    rate: 30,
    skills: ["Node.js", "Express", "PostgreSQL", "Docker", "TypeScript"],
    readinessScore: 80,
    readinessStatus: READINESS_STATUS.IN_2_WEEKS,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    about: "Backend developer with a focus on scalable microservices.",
  },
  {
    id: "c3",
    name: "Dmitry Sokolov",
    role: "Fullstack Developer",
    grade: GRADE.SENIOR,
    format: FORMAT.HYBRID,
    rate: 55,
    skills: ["React", "Node.js", "AWS", "GraphQL", "MongoDB", "TypeScript"],
    readinessScore: 60,
    readinessStatus: READINESS_STATUS.LOOKING_FOR_OFFERS,
    avatarUrl: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    about: "Fullstack wizard who builds products from scratch.",
  },
  {
    id: "c4",
    name: "Elena Petrova",
    role: "UI/UX Designer",
    grade: GRADE.MIDDLE,
    format: FORMAT.OFFICE,
    rate: 25,
    skills: ["Figma", "Sketch", "Prototyping", "User Research", "CSS"],
    readinessScore: 90,
    readinessStatus: READINESS_STATUS.READY,
    avatarUrl: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    about: "Designer focused on creating beautiful and functional user experiences.",
  },
  {
    id: "c5",
    name: "Igor Popov",
    role: "DevOps Engineer",
    grade: GRADE.LEAD,
    format: FORMAT.REMOTE,
    rate: 70,
    skills: ["Kubernetes", "AWS", "Terraform", "CI/CD", "Linux", "Python"],
    readinessScore: 40,
    readinessStatus: READINESS_STATUS.BUSY,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026703d",
    about: "Automating all the things since 2010.",
  },
  {
    id: "c6",
    name: "Anna Kuznetsova",
    role: "Frontend Developer",
    grade: GRADE.JUNIOR,
    format: FORMAT.OFFICE,
    rate: 15,
    skills: ["HTML", "CSS", "JavaScript", "React"],
    readinessScore: 100,
    readinessStatus: READINESS_STATUS.READY,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026705d",
    about: "Passionate junior developer eager to learn and grow.",
  },
  {
    id: "c7",
    name: "Sergey Volkov",
    role: "Backend Developer",
    grade: GRADE.SENIOR,
    format: FORMAT.REMOTE,
    rate: 60,
    skills: ["Go", "Python", "Kubernetes", "PostgreSQL", "Redis"],
    readinessScore: 85,
    readinessStatus: READINESS_STATUS.READY,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026706d",
    about: "High-load systems architect and backend specialist.",
  },
  {
    id: "c8",
    name: "Tatiana Morozova",
    role: "QA Engineer",
    grade: GRADE.MIDDLE,
    format: FORMAT.HYBRID,
    rate: 20,
    skills: ["Selenium", "Cypress", "Postman", "Manual Testing"],
    readinessScore: 75,
    readinessStatus: READINESS_STATUS.IN_2_WEEKS,
    avatarUrl: "https://i.pravatar.cc/150?u=a042581f4e29026707d",
    about: "Detail-oriented QA ensuring top-notch software quality.",
  }
];

export const mockPipelineCandidates: import("./types").PipelineCandidate[] = mockCandidates.map((c, i) => {
  const stages = Object.values(PIPELINE_STAGE);
  return {
    ...c,
    pipelineStage: stages[i % stages.length],
    lastUpdated: new Date(Date.now() - i * 1000 * 60 * 60 * 24).toISOString(),
  };
});
